#!/usr/bin/env python3
"""Compile Localizable.xcstrings into <locale>.lproj/Localizable.strings inside a resource bundle.

`swift build` (the native SwiftPM backend) copies `.process` resources unchanged, so the
string catalog is not compiled into the per-locale tables that NSLocalizedString reads.
build-app.sh runs this on the copied SwiftPM resource bundle.

The tables are written in the classic **OpenStep** strings format, UTF-16LE with a
byte-order mark:

    "key" = "value";

CFBundle's strings loader only accepts that representation. A binary or XML property
list reads back fine through `NSDictionary(contentsOfFile:)` and `plutil`, so the table
looks correct on disk, but `NSLocalizedString` ignores it and returns the English key -
which is exactly the bug this format choice avoids.

Usage:
    compile-localizations.py <Localizable.xcstrings> <bundle-dir>
    compile-localizations.py --self-test        # round-trip the encoder, no I/O
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

BOM_UTF16LE = b"\xff\xfe"
HEADER = "/* Generated by Scripts/compile-localizations.py - do not edit. */\n"

# Escapes understood by the OpenStep strings parser. Anything else that is not
# printable is emitted as \Uxxxx, which the same parser also accepts.
_SIMPLE_ESCAPES = {
    "\\": "\\\\",
    '"': '\\"',
    "\n": "\\n",
    "\r": "\\r",
    "\t": "\\t",
}


def escape(text: str) -> str:
    """Escape a key or value for the OpenStep strings format."""
    out = []
    for character in text:
        escaped = _SIMPLE_ESCAPES.get(character)
        if escaped is not None:
            out.append(escaped)
        elif ord(character) < 0x20 or ord(character) == 0x7F:
            out.append(f"\\U{ord(character):04x}")
        else:
            out.append(character)
    return "".join(out)


def render_strings(table: dict[str, str]) -> bytes:
    """Render one locale table as OpenStep strings bytes (UTF-16LE + BOM)."""
    lines = [HEADER]
    for key in sorted(table):
        lines.append(f'"{escape(key)}" = "{escape(table[key])}";\n')
    return BOM_UTF16LE + "".join(lines).encode("utf-16-le")


def parse_strings(data: bytes) -> dict[str, str]:
    """Decode a table rendered by `render_strings`.

    Only used by the self-test: it is a reader for the exact subset this script
    writes, not a general OpenStep parser.
    """
    if data[:2] == BOM_UTF16LE:
        text = data[2:].decode("utf-16-le")
    elif data[:2] == b"\xfe\xff":
        text = data[2:].decode("utf-16-be")
    else:
        text = data.decode("utf-8")

    table: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("/*") or line.startswith("//"):
            continue
        if not (line.startswith('"') and line.endswith('";')):
            raise ValueError(f"malformed strings line: {line!r}")
        line = line[1:-2]
        key, _, value = line.partition('" = "')
        if not _:
            raise ValueError(f"malformed strings entry: {line!r}")
        table[unescape(key)] = unescape(value)
    return table


def unescape(text: str) -> str:
    """Inverse of `escape` for the subset written above."""
    out = []
    index = 0
    while index < len(text):
        character = text[index]
        if character != "\\":
            out.append(character)
            index += 1
            continue
        marker = text[index + 1]
        if marker == "U":
            out.append(chr(int(text[index + 2 : index + 6], 16)))
            index += 6
        else:
            out.append({"n": "\n", "r": "\r", "t": "\t", '"': '"', "\\": "\\"}[marker])
            index += 2
    return "".join(out)


def catalog_tables(catalog_path: Path) -> dict[str, dict[str, str]]:
    """Flatten the string catalog into one table per locale (English included)."""
    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
    tables: dict[str, dict[str, str]] = {}
    for key, entry in catalog.get("strings", {}).items():
        for locale, localization in entry.get("localizations", {}).items():
            tables.setdefault(locale, {})[key] = localization["stringUnit"]["value"]
    return tables


def main() -> int:
    arguments = sys.argv[1:]
    if arguments == ["--self-test"]:
        return self_test()
    if len(arguments) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    catalog_path, bundle_dir = Path(arguments[0]), Path(arguments[1])
    tables = catalog_tables(catalog_path)

    for locale, table in sorted(tables.items()):
        directory = bundle_dir / f"{locale}.lproj"
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "Localizable.strings").write_bytes(render_strings(table))

    locales = ", ".join(sorted(tables))
    entries = sum(len(table) for table in tables.values())
    print(
        f"Compiled {len(tables)} localization tables ({entries} entries) into {bundle_dir}: {locales}"
    )
    return 0


def self_test() -> int:
    """Round-trip the encoder over the awkward cases the catalog contains."""
    sample = {
        "Settings": "Настройки",
        "agent × %d": "агент × %d",
        "quotes": 'POST {"session": "id"} and "quoted" text',
        "backslash": "C:\\Users\\cat",
        "newline": "first line\nsecond line",
        "tabs": "a\tb",
        "percent": "100%% done, %@ left, %d more",
        "empty": "",
        "emoji": "🐱 watermelon",
    }
    decoded = parse_strings(render_strings(sample))
    if decoded != sample:
        for key in sorted(sample):
            if decoded.get(key) != sample[key]:
                print(f"self-test: {key!r} -> {decoded.get(key)!r}, expected {sample[key]!r}", file=sys.stderr)
        return 1
    data = render_strings(sample)
    if not data.startswith(BOM_UTF16LE):
        print("self-test: table is missing the UTF-16LE byte-order mark", file=sys.stderr)
        return 1
    print(f"self-test: OpenStep strings round-trip ok ({len(sample)} entries, {len(data)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
